### ISSUE TITLE
changed stock names

### ISSUE THREAD

**Issue by Philipp-Neubauer** [Philipp-Neubauer/FirstAssessment#11]
Mike; 

Still hunting down matching issues.

It looks as though some of the non-matching is due to names having changed in the main management DB, but not in the others; can you just conform that all stocks with "pre-IQ" now don't have this label anymore? 

I can easily replace that in all the other tables (land-price and crossref) - if that's the only change.

**Comment by mcmelnychuk** [comment]
Ah, my bad, the 'pre-IQ' was poor notation on my part years ago. I did change those names recently in the files (so it wouldn't conflict with some of the linkage tables I was working with), but it looks like I missed making those some changes in some other files. All I did for those changes was to delete " pre-IQ" including the leading space.

**Comment by Philipp-Neubauer** [comment]
Fixed these in the dropbox csv's
